### ISSUE TITLE
TODO: 對接 google sheet 取資料

### ISSUE THREAD

**Issue by Prysline** [Jackal-and-Platypus/SheetScraper#2]
### 目標
從 google sheet 取得字串資料並整理成所需規格回傳。

### 功能描述
1. 使用 API 從 google sheet 取得測試計畫內容
2. 根據 plan 分頁取得 test suite 資料
3. 讀取每個 test suite 中的 case，紀錄步驟並回傳指定規格的資料

### 預期結果
以[plan頁面](https://reurl.cc/2LVXb4)為例，應能取得 test suite 列表。
以[suite頁面](https://reurl.cc/o7AlKg)為例。
讀取 test case 的列表時應回傳：
```python
return [
	{"name": "註冊",
	"steps": [
		{"action_type":"link" , "by_method":"link_text", "by_value":"註冊", "value": "/tplanet_signup.html"},
		{"action_type":"input" , "by_method":"id", "by_value":"email", "value": "test1@test.com"},
		...{}]
	},
	{"name": "登入", steps: [] }
]
```
讀取單一 test case 的步驟列表時應回傳：
```python
return [
	{"action_type":"link" , "by_method":"link_text", "by_value":"註冊", "value": "/tplanet_signup.html"},
	{"action_type":"input" , "by_method":"id", "by_value":"email", "value": "test1@test.com"},
	...{}
]
```

### 任務清單
- [x] 驗證 API
- [x] 從 test plan 取得 test suite 列表
- [x] 從 test suite 工作分頁取得單一 case 的步驟列表
	- 步驟中有值為空時，請填入 None
- [x] 從 test suite 工作分頁取得 case 列表

### 相關連結
- [相關連結集中](https://reurl.cc/o7Mq3j)
- [參考plan頁面](https://reurl.cc/2LVXb4)
- [參考suite頁面](https://reurl.cc/o7AlKg)

### 後續步驟
- 將測試結果(Boolean) 寫回 test plan 中（每個 suite 的成功或失敗）
#### 其他問題
- 是否需要將每個 case 的測試結果寫回試算表？（或是只在最後產出的 report 上紀錄就好？）

**Comment by mikazukiyeh** [comment]
我這邊上傳到分支 gsheet囉 QQ但有點問題

**Comment by mikazukiyeh** [comment]
目前需求我應該都做完了，再請確認一下格式!!!拜託了

**Comment by Prysline** [comment]
感謝你！
格式方面都沒問題！

目前還有幾項要調整的內容：
1. **class `SheetScraper` 改名為 `GsheetManager`** 
2. **相同 code 出現在不同 function 中**
    我注意到下列的 code 重複出現（變數名稱不同，但=後方都一致）：
    ```python
        spreadsheet = self.client.open_by_url(self.spreadsheet_url)
        sheet = spreadsheet.worksheet_by_title(self.sheet_name)
        data = sheet.get_all_records()
    ```
    像這樣用途一致、完全相同的 code 可以抽取出來寫成一個獨立 function，往後要做類似操作時只要呼叫這個 functon 就好。
    將相同的 code 抽取出來寫成 function 的好處是，如果未來有需要修改或調整這個功能的內容，只要修改一個地方就好，不需要修改每個重複使用的地方，節省大量工作量。
    ※ function 設計原則可以參考[Clean Code (3) — 函式 (Functions)](https://medium.com/@corrupt003/clean-code-3-%E5%87%BD%E5%BC%8F-4adc56e9a329)這篇

3. **將 `sheet_name` 從 `__init__` 中抽出**
    從測試用的 `if __name__ == "__main__"` 中，我發現你的呼叫方法是先個別產生一個 `SheetScraper` 實體物件，再用這個物件去呼叫 `get_steps()` 和 `get_plan()`。
    這兩個物件的 `credentials_path` 和 `spreadsheet_url` 都相同，變更的只有 `sheet_name`，因為每次創建一個實體物件都會進行一次驗證過程，可能會導致不必要的連接和資源占用。

    在實際使用中，我們會經常變更 `sheet_name`，你可以新增一個 `set_sheet_name` 的 function，就能在需要時變更同一物件的屬性。

4. **新增能取得單一 case 的 function**
    新增的需求。
    給予 case 名稱並呼叫該 function 會回傳：
    ```python
    {'name': '註冊', 'steps': [{'action_type': 'link', 'by_method': 'link_text', 'by_value': '註冊', 'value': '/tplanet_signup.html'}, {'action_type': 'input', 'by_method': 'id', 'by_value': 'email', 'value': 'test1@test.com'}, {'action_type': 'input', 'by_method': 'id', 'by_value': 'username', 'value': 'test1'}, {'action_type': 'input', 'by_method': 'id', 'by_value': 'password', 'value': 12345678}, {'action_type': 'input', 'by_method': 'id', 'by_value': 'cfm_password', 'value': 'cfm_password'}, {'action_type': 'click', 'by_method': 'xpath', 'by_value': "//button[text()='註冊']", 'value': '/backend/cms_ab.html'}]}
    ```
    
    
### TASKS
- [x]  class `SheetScraper` 改名為 `GsheetManager`
- [x] 抽出重複使用的 code 新增 function
- [x] 將 `sheet_name` 從 `__init__` 中抽出
- [x] 新增能取得單一 case 的 function

再麻煩 Luna 了，感謝！

**Comment by mikazukiyeh** [comment]
這邊更新好了!
